### ISSUE TITLE
Fatal error: Compatibility issue with FS Edd Migration plugin

### ISSUE THREAD

**Issue by MarkHollo** [TablePress/TablePress#182] opened 2023-09-22 09:00 UTC
Howdy!

We wanted to use your plugin on our site to give it a test drive, but because we're using Freemius as you guys and have the EDD Migration plugin installed, it's causing a fatal error.

You're not the only ones with this problem, but perhaps it would be great if all of us would be able to use each other's products :D 

The error: Fatal error: Cannot redeclare fs_find_caller_plugin_file() (previously declared in /public_html/wp-content/plugins/tablepress/libraries/freemius/includes/fs-essential-functions.php:184 in /wp-content/plugins/edd-migration-develop/includes/fs-essential-functions.php on line 245

To avoid confusion, I'm referring to this plugin and line in question: https://github.com/Freemius/edd-migration/blob/master/includes/fs-essential-functions.php#L245

The function in your file: https://github.com/TablePress/TablePress/blob/main/libraries/freemius/includes/fs-essential-functions.php#L178

Any chance you guys can do something about it? Appreciate it in advance

**Comment by TobiasBg** [comment] 2023-09-22 09:13
Hi @MarkHollo,

thanks for opening this issue!
Now, I don't think that there's anything that I can do about this, I'm afraid, as this seems to be an issue with either that EDD Migration plugin or with the Freemius SDK.
In both cases, code changes or fixed would have to be done by Freemius.

I would therefore suggest that you get in touch with Freemius about this. From what I can see, an easy fix could be to wrap those functions in a `function_exists()` call in that EDD migration plugin (maybe that's even something that you could try yourself?).

Best wishes,
Tobias

**Comment by TobiasBg** [comment] 2023-09-22 09:14
@Freemius @vovafeldman Can you maybe take a look?

**Comment by MarkHollo** [comment] 2023-09-22 09:54
Hi @TobiasBg! Thanks for responding.

I did raise that issue with them, in April actually. Since there have been no changes, I was thinking that there might be something you guys could do faster because it's affecting your integration because this wasn't a problem until this year. I can wrap things up in function_exists but not sure this is a permanent solution for everyone

**Comment by TobiasBg** [comment] 2023-09-22 10:15
Hi @MarkHollo,

oh, ok. Yes, it appears that their EDD migration plugin is only updated once in a while. :-(

I'm not sure what I can do here, to be honest. Even if I knew what to change, I don't really want to make code changes in the Freemius SDK that ships with TablePress, as that would just introduce another maintenance burden, whenever they release a new SDK version.

I believe the cause of the issue is the EDD migration plugin here. So, I think the `function_exists()` in your copy of the EDD migration plugin would be the safest (and easiest) starting point here. Maybe you can then even open a Pull Request with these changes, so that they'll eventually benefit all users of that migration plugin.

Best wishes,
Tobias

P.S.: You are probably only seeing this with TablePress this year, because I only started using the Freemius SDK in TablePress 2.0, which was released in late December of last year.

**Comment by MarkHollo** [comment] 2023-09-22 10:35
Hi @TobiasBg, we need that plugin as you need the function, and there are slightly different codes, so not sure this is the right solution.

On the other hand, it will be a problem when using any plugin that using the same function as yours, so not sure where the solution should be implemented but we can agree this needs a solution

**Comment by TobiasBg** [comment] 2023-09-22 13:56
Hi @MarkHollo,

well, right now, both that EDD migration plugin and plugins that use the Freemius SDK (like TablePress) seem to load that `fs_find_caller_plugin_file()` function. Even though they look slightly different, I think they still do the same. Thus, I think it's fine for the EDD migration plugin to also use the function from the SDK here.
To guarantee that, a `function_exists()` wrapper around the definition in that file (or just commenting out the definition) should work fine. From what I can see, `function_exists()` is wrapped around several other functions in that file as well, maybe it missing for `fs_find_caller_plugin_file()` is just an oversight.

As that function and file are Freemius files that I can not directly change, there's really nothing that I can do about this in TablePress.

Best wishes,
Tobias

**Comment by vovafeldman** [comment] 2023-09-24 07:20
@MarkHollo @TobiasBg I reviewed the method, and the one in the EDD is simply an outdated version. Both intended to do the same thing. One needs to be updated.

I pushed a fix to the EDD migration `develop` branch: https://github.com/Freemius/edd-migration/commit/2178829e241e6586c4c6f0440403026d84d4add8

And we'll wrap the method in the SDK (probably on the next release, not the upcoming one). But you can patch those on your WP setup, and it should work just fine.

**Comment by TobiasBg** [comment] 2023-09-24 11:28
Hi @vovafeldman,

thanks for taking a look here! Thanks for confirming my assumption!
@MarkHollo, I think using the version from the `develop` branch should indeed be the best solution here then.

As there's nothing really left here for TablePress to do, I'll go ahead and close this issue. Feel free to continue adding any findings, of course!

Best wishes,
Tobias

**Closed by TobiasBg** 2023-09-24 11:28 UTC
